source 'https://rubygems.org'

gem 'htmlentities', '~>4.3'
gem 'nokogiri',     '>= 1.4.4'
gem 'activerecord', '~>3.2.9'
gem 'activesupport', '~>3.2.9'
gem 'rspec'
gem 'kwalify', '~>0.7'
gem 'actionmailer', '~>3.2.9'
gem 'sqlite3', '~>1.3'
gem 'typhoeus', '~>0.5'
gem 'money', '~>5.0.0'
